const API_URL='https://script.google.com/macros/s/AKfycbz5xwcHaE1sLcV_9Fpp_8n5-9snWlYZa6lJSLKM-M2pgHeAH6VmWHIvnVwhT84BG8kj/exec';
const tg=window.Telegram?.WebApp||null;if(tg){tg.ready();tg.expand();tg.setHeaderColor('#ffffff');tg.setBackgroundColor('#fff7fb')}
const initData=tg?.initData||'';const $=id=>document.getElementById(id);
const products=[
{id:1,name:'MAMA Noodle',price:1.00,cat:'Food',image:'assets/mama.png'},
{id:2,name:'Indomie Noodles 80g',price:.85,cat:'Food',image:'assets/indomie.png'},
{id:3,name:'Coca Cola 330ml',price:.75,cat:'Drinks',image:'assets/coke.png'},
{id:4,name:"Lay's Potato Chips",price:1.20,cat:'Snacks',image:'assets/lays.png'},
{id:5,name:'Angkor Puro Water 500ml',price:.30,cat:'Drinks',image:'assets/water.png'},
{id:6,name:'Colgate Toothpaste 100g',price:1.50,cat:'Personal Care',image:'assets/colgate.png'}
];
let cart=JSON.parse(localStorage.getItem('lyjing_cart')||'[]');let category='All';let delivery='Delivery';
function save(){localStorage.setItem('lyjing_cart',JSON.stringify(cart));updateBadge()}
function updateBadge(){const n=cart.reduce((a,x)=>a+x.qty,0);['cartBadge','cartNavBadge'].forEach(id=>{if($(id))$(id).textContent=n})}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));if(id==='home')document.querySelectorAll('.nav')[0]?.classList.add('active');if(id==='orders')document.querySelectorAll('.nav')[3]?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderCategories(){const cats=['All',...new Set(products.map(p=>p.cat))];$('categories').innerHTML=cats.map(c=>`<button class="chip ${category===c?'active':''}" onclick="category='${c}';renderCategories();renderProducts()">${c}</button>`).join('')}
function productCard(p){return `<article class="product"><div class="product-photo" onclick="detail(${p.id})"><img src="${p.image}" alt="${p.name}"></div><h3 onclick="detail(${p.id})">${p.name}</h3><div class="cat">${p.cat}</div><div class="price">$${p.price.toFixed(2)}</div><button class="add-btn" onclick="add(${p.id})">🛒 Add to cart</button></article>`}
function renderProducts(){const q=(( $('search')?.value||'')+' '+($('shopSearch')?.value||'')).toLowerCase().trim();const list=products.filter(p=>(category==='All'||p.cat===category)&&p.name.toLowerCase().includes(q));$('homeProducts').innerHTML=list.slice(0,6).map(productCard).join('')||emptyProducts();$('shopProducts').innerHTML=list.map(productCard).join('')||emptyProducts()}
function emptyProducts(){return '<div class="card" style="grid-column:1/-1;text-align:center">No products found.</div>'}
function detail(id){const p=products.find(x=>x.id===id);window.tempQty=1;$('detailContent').innerHTML=`<div class="page-head"><button onclick="showScreen('shop')">‹</button><h2>Product</h2></div><div class="detail-card"><div class="detail-photo"><img src="${p.image}" alt="${p.name}"></div><h1>${p.name}</h1><div class="cat">${p.cat}</div><div class="price">$${p.price.toFixed(2)}</div><p>Quality product from LY JING Mart. Available for delivery or pickup.</p><div class="qty-row"><button onclick="changeTemp(-1)">−</button><b id="tempQty">1</b><button onclick="changeTemp(1)">+</button></div><button class="primary full" onclick="addMany(${p.id})">🛒 Add to Cart</button></div>`;showScreen('detail')}
function changeTemp(n){window.tempQty=Math.max(1,window.tempQty+n);$('tempQty').textContent=window.tempQty}
function addMany(id){for(let i=0;i<window.tempQty;i++)add(id);openCart()}
function add(id){const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();toast('Added to cart')}
function openCart(){renderCart();showScreen('cart')}
function renderCart(){if(!cart.length){$('cartContent').innerHTML='<div class="card" style="text-align:center;padding:45px 12px"><div style="font-size:42px">🛒</div><h3>Your cart is empty</h3><button class="primary full" onclick="showScreen(\'shop\')">Start Shopping</button></div>';return}let subtotal=0;const rows=cart.map(x=>{const p=products.find(p=>p.id===x.id);if(!p)return '';subtotal+=p.price*x.qty;return `<div class="cart-row"><div class="cart-thumb"><img src="${p.image}" alt=""></div><div class="grow"><b>${p.name}</b><div class="price" style="font-size:14px">$${p.price.toFixed(2)}</div></div><div class="qty-box"><button onclick="changeCart(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeCart(${p.id},1)">+</button></div></div>`}).join('');$('cartContent').innerHTML=rows+`<div class="card"><div class="summary-line"><span>Subtotal</span><b>$${subtotal.toFixed(2)}</b></div><div class="summary-line"><span>Delivery</span><b id="cartDeliveryFee">Calculated at checkout</b></div></div><button class="primary full" onclick="prepareCheckout()">Checkout <span>›</span></button>`}
function changeCart(id,n){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function prepareCheckout(){if(!cart.length)return;const phone=localStorage.getItem('lyjing_phone')||'';if(phone)$('phone').value=phone;fillProvinces();setDelivery(delivery);renderCheckoutSummary();showScreen('checkout')}
const provinces=['Phnom Penh','Banteay Meanchey','Battambang','Kampong Cham','Kampong Chhnang','Kampong Speu','Kampong Thom','Kampot','Kandal','Kep','Koh Kong','Kratie','Mondulkiri','Oddar Meanchey','Pailin','Preah Sihanouk','Preah Vihear','Pursat','Ratanakiri','Siem Reap','Stung Treng','Svay Rieng','Takeo','Tboung Khmum'];
function fillProvinces(){const s=$('province');if(s.options.length>1)return;s.innerHTML='<option value="">Select province</option>'+provinces.map(p=>`<option>${p}</option>`).join('')}
function setDelivery(type){delivery=type;$('deliveryBtn').classList.toggle('active',type==='Delivery');$('pickupBtn').classList.toggle('active',type==='Pickup');$('deliveryFields').classList.toggle('hidden',type!=='Delivery');$('pickupInfo').classList.toggle('hidden',type!=='Pickup');renderCheckoutSummary()}
function calc(){const subtotal=cart.reduce((a,x)=>{const p=products.find(p=>p.id===x.id);return a+(p?p.price*x.qty:0)},0);let fee=0;if(delivery==='Delivery'){const p=$('province')?.value||'';fee=p?(p==='Phnom Penh'?1.5:2.5):0}return{subtotal,fee,total:subtotal+fee}}
function renderCheckoutSummary(){const c=calc();$('checkoutSummary').innerHTML=`<div class="summary-line"><span>Items</span><b>$${c.subtotal.toFixed(2)}</b></div><div class="summary-line"><span>Delivery</span><b>$${c.fee.toFixed(2)}</b></div><div class="summary-line total"><span>Total</span><b>$${c.total.toFixed(2)}</b></div>`}
function updateCheckoutTotals(){renderCheckoutSummary()}
function requestPhone(){if(tg?.requestContact){tg.requestContact(ok=>{if(ok){toast('Telegram contact shared');setTimeout(()=>location.reload(),500)}})}else{toast('Please enter your phone number') } }
function submitOrder(e){e.preventDefault();if(!initData){toast('Please open LY JING Mart from Telegram.');return}if(!cart.length){toast('Your cart is empty');return}const phone=$('phone').value.trim();if(!phone){toast('Phone number is required');return}const province=delivery==='Delivery'?$('province').value:'';if(delivery==='Delivery'&&!province){toast('Please select your province');return}const c=calc();const orderId='#LJM'+Date.now().toString().slice(-7);const order={orderId,items:cart.map(x=>{const p=products.find(p=>p.id===x.id);return{name:p.name,price:p.price,qty:x.qty}}),subtotal:Number(c.subtotal.toFixed(2)),delivery,province,customer:{phone},note:$('note').value.trim()};localStorage.setItem('lyjing_phone',phone);const btn=$('placeBtn');btn.disabled=true;btn.textContent='Sending order…';fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({initData,order})}).then(r=>r.json()).then(data=>{if(!data.success)throw new Error(data.error||'Order could not be submitted.');$('successOrder').textContent=orderId;cart=[];save();$('checkoutForm').reset();delivery='Delivery';showScreen('success');toast('Order sent successfully')}).catch(err=>{toast(err.message||'Could not send order');btn.disabled=false;btn.innerHTML='Confirm Order <span>›</span>'})}
async function loadOrders(){if(!initData){$('ordersContent').innerHTML='<div class="loading">Open the shop from Telegram to view your orders.</div>';return}$('ordersContent').innerHTML='<div class="loading">Loading orders…</div>';try{const url=API_URL+'?action=history&initData='+encodeURIComponent(initData);const r=await fetch(url);const data=await r.json();if(!data.success)throw new Error(data.error||'Could not load orders');if(!data.orders?.length){$('ordersContent').innerHTML='<div class="loading">No orders yet.</div>';return}$('ordersContent').innerHTML=data.orders.map(o=>`<div class="order-card"><div class="order-top"><span class="order-id">${o.orderId}</span><span class="status">${o.paymentStatus||'Pending'}</span></div><div class="order-meta">${o.createdAt||''} · ${o.delivery||''} ${o.province?'· '+o.province:''}</div><div class="order-items">${(o.items||[]).map(i=>`${i.name} × ${i.qty}`).join('<br>')}</div><div class="order-total"><span>Total</span><b>$${Number(o.invoiceTotal||o.subtotal||0).toFixed(2)}</b></div></div>`).join('')}catch(e){$('ordersContent').innerHTML='<div class="loading">Unable to load orders right now.</div>'}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function init(){updateBadge();renderCategories();renderProducts();$('tgUser').textContent=tg?.initDataUnsafe?.user?`Connected: ${tg.initDataUnsafe.user.first_name||'Telegram customer'}`:'Telegram account connected';const saved=localStorage.getItem('lyjing_phone');if(saved)$('phone').value=saved;fillProvinces()}
init();
